// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub enum IncomeEmploymentIncomeEmploymentType {
    #[serde(rename = "Contract")]
    Contract,

    #[serde(rename = "Hourly")]
    Hourly,

    #[serde(rename = "Salaried")]
    Salaried,
}
