// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct IncomePassiveIncome {
    #[serde(rename = "amount")]
    pub amount: String,

    #[serde(rename = "incomeType")]
    pub incomeType0: IncomePassiveIncomeIncomeType,

    #[serde(rename = "passiveIncomeType")]
    pub passiveIncomeType: IncomePassiveIncomePassiveIncomeType,

    #[serde(rename = "source")]
    pub source: String,
}
