// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct IncomeEmploymentIncome {
    #[serde(rename = "amount")]
    pub amount: String,

    #[serde(rename = "employmentType")]
    pub employmentType: IncomeEmploymentIncomeEmploymentType,

    #[serde(rename = "incomeType")]
    pub incomeType0: IncomeEmploymentIncomeIncomeType,

    #[serde(rename = "source")]
    pub source: String,
}
