// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub enum IncomeEmploymentIncomeIncomeType {
    #[serde(rename = "Employment")]
    Employment,

    #[serde(rename = "Passive")]
    Passive,
}
