// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
#[serde(tag = "incomeType")]
pub enum Income {
    #[serde(rename = "EmploymentIncome")]
    EmploymentIncome(IncomeEmploymentIncome),

    #[serde(rename = "PassiveIncome")]
    PassiveIncome(IncomePassiveIncome),
}

#[derive(Serialize, Deserialize)]
pub enum IncomeEmploymentIncomeEmploymentType {
    #[serde(rename = "Contract")]
    Contract,

    #[serde(rename = "Hourly")]
    Hourly,

    #[serde(rename = "Salaried")]
    Salaried,
}

#[derive(Serialize, Deserialize)]
pub enum IncomeEmploymentIncomeIncomeType {
    #[serde(rename = "Employment")]
    Employment,

    #[serde(rename = "Passive")]
    Passive,
}

#[derive(Serialize, Deserialize)]
pub struct IncomeEmploymentIncome {
    #[serde(rename = "amount")]
    pub amount: String,

    #[serde(rename = "employmentType")]
    pub employmentType: IncomeEmploymentIncomeEmploymentType,

    #[serde(rename = "incomeType")]
    pub incomeType0: IncomeEmploymentIncomeIncomeType,

    #[serde(rename = "source")]
    pub source: String,
}

#[derive(Serialize, Deserialize)]
pub enum IncomePassiveIncomeIncomeType {
    #[serde(rename = "Employment")]
    Employment,

    #[serde(rename = "Passive")]
    Passive,
}

#[derive(Serialize, Deserialize)]
pub enum IncomePassiveIncomePassiveIncomeType {
    #[serde(rename = "Investment")]
    Investment,

    #[serde(rename = "Rental")]
    Rental,

    #[serde(rename = "Royalties")]
    Royalties,
}

#[derive(Serialize, Deserialize)]
pub struct IncomePassiveIncome {
    #[serde(rename = "amount")]
    pub amount: String,

    #[serde(rename = "incomeType")]
    pub incomeType0: IncomePassiveIncomeIncomeType,

    #[serde(rename = "passiveIncomeType")]
    pub passiveIncomeType: IncomePassiveIncomePassiveIncomeType,

    #[serde(rename = "source")]
    pub source: String,
}
