// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct PlanetResponse {
    #[serde(rename = "Count")]
    pub count: i32,

    #[serde(rename = "Next")]
    pub next: String,

    #[serde(rename = "Results")]
    pub results: Vec<Planet>,
}
